channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-desolve
  - r-ggplot2
  - r-glue
  - r-knitr
  - r-rmarkdown
#  - r-socialmixr
  - r-tidyverse
  - r-covr
  - r-dplyr
  - r-forcats
  - r-gridextra
  - r-magrittr
  - r-markdown
  - r-methods
  - r-reshape2
  - r-rlang
  - r-rmarkdown
  - r-testthat
  - r-viridis
